"""added tables

Revision ID: 65a2402b2502
Revises: 202eb63b6191
Create Date: 2025-05-21 20:51:38.731139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65a2402b2502'
down_revision: Union[str, None] = '202eb63b6191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_owner_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_owner_id'], ['business_owners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('commision', sa.Float(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_date', 'service_id', name='service_book_unique')
    )
    op.create_index(op.f('ix_service_booking_booking_date'), 'service_booking', ['booking_date'], unique=False)
    op.create_index(op.f('ix_service_booking_service_id'), 'service_booking', ['service_id'], unique=False)
    op.add_column('services', sa.Column('quantity', sa.Integer(), server_default='0', nullable=True))
    op.alter_column('services', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'not defined'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'not defined'::character varying"))
    op.drop_column('services', 'quantity')
    op.drop_index(op.f('ix_service_booking_service_id'), table_name='service_booking')
    op.drop_index(op.f('ix_service_booking_booking_date'), table_name='service_booking')
    op.drop_table('service_booking')
    op.drop_table('purchases')
    op.drop_table('notifications')
    # ### end Alembic commands ###
